// src/lib/components/TextInput.svelte
<script lang="ts">
	import { createEventDispatcher } from 'svelte';

	const dispatch = createEventDispatcher();

	const onEnter = (e: KeyboardEvent) => e.key === 'Enter' && dispatch('enter');

	export let label: string;

	export let required = false;

	export let value = '';
</script>

<!--
	@component
	Text input with a label, ignored when the value is empty and not required.
-->
<label class="flex items-center gap-3">
	<span class="select-none text-nowrap font-semibold text-white {$$props.class ?? ''}">{label}</span>
	<input form="" type="text" bind:value class="rounded-lg border-0 focus:ring-0" on:click on:keydown={onEnter} />
	{#if required || value}
		<input type="hidden" {required} {value} {...$$restProps} />
	{/if}
</label>

// src/app/search/TextInput.tsx
import type { HTMLProps } from 'react';

export type TextInputProps = Readonly<HTMLProps<HTMLInputElement> & { label?: string }>;

export default function TextInput({ label, type, className, required, ...props }: Readonly<TextInputProps>) {
	return (
		<label className="block">
			{label && <span className="mb-1 block select-none text-nowrap text-xs font-medium text-gray-700">{label}</span>}
			<input
				type={type || 'text'}
				className={`block w-full rounded px-1.5 py-1.5 text-sm focus:border-green-500 focus:outline-none focus:ring-green-500 ${className || ''}`}
				required={required}
				{...props}
			/>
		</label>
	);
}
